# S3 bucket for storing lambda function code
resource "aws_s3_bucket" "spooky_days_lambda_bucket" {
  bucket = "${var.app_name}-lambda-bucket-${random_string.random.result}"
}

# S3 bucket for storing images generated by OpenAI
resource "aws_s3_bucket" "spooky_days_image_bucket" {
  bucket = "${var.app_name}-image-bucket-${random_string.random.result}"
}
